###buy-sell agreement: 

Why we need buy-sell agreement? 
Because closely held businesses are not marketable and create liquidity problems when one of the business partners wishes to terminate and transfer of ownership. 

The CFP exam would focus on the buy-sell agreement at the death of an owner funded through the use of life insurance. 

Two methods in transferring ownership: 
* Each owner owning an insurance policyt on each of the other owners. The estate of each owner then commits to selling the ownership to the surviving owners. 

The characteristics of buy-sell agreement: 
- each shareholder owns a policy on all of the other owners 
- premiums are nondeductible 
- life insurance cannot be attached to the creditors 
- tax-free benefits to the remaning owners 
- step-up basis, of remaining owners' interests 

Good side: (1) Step-up basis (2) life insurance can not be attached by the company's creditors 
Bad side: (1) own a policy on each of the other owners, the formula to determine the number of policies is N * (N - 1) 

Another way: stock redemption owning the life policies with each other , they commmit to sell their ownership back to the company 

- company owns a policy on each other 
- premiums are not deductible 
- company purchases deceased owner's interests 
- no step-up in basis of remaining owner's interest 
- does not allow for an altering of ownership ratios 

good: this allows the company to purchase one policy on each owner which siginificantly reduce the number of policies required if there are several owners. the entity 
insurance is that the number of the policies is reduced to one policy per partner or shareholder. 
bad: the remaining owners did not get a step-up basis 

Special Election and postmortem planning: 
- **liquidity needs:**
The ILET ( Irrevocable Life Insurance Trust) is not included in the decendent's gross estate. 
*  Last medical costs 
*  Funeral Costs 
*  Transisiont of Adjustment Period costs 
*  Administrative Costs 
*  Income Estate, and GSTT 
   they should have enough money to cover this costs 
   
 ** Liquidity Sources and Implication** : How to use liquidate the liquidity to cover all the costs 
 - Sale of Assets 
 - Life Insurance 
 - Tax Advantage Account 
    The value of those deferrals at death will not qualify for a step-up in basis 
    The bene of the tax-advantaged account will be eligible for a deduction in the form of a miscellaneous itemized deduction not subject to 2% of AGI floor. 
    However, they had the income-tax on these accounts 

** Coporate Redemption from closely held businesses 
   C-corp held to cover estate liquidity needs-the corporation itself. This kind of redemption can transform an illiquid asset into a liquid asset. 
   more than 35% of the decedent's adjusted gross estate must consist of the closely held business interests. The FMV of all of the closely held business interests can be 
   aggregated to meet the 35% test if the decedent owned at least 20% of each company's outstanding stocks. 
   
** Distribution of Assets: 
   Administrator will distribute the estate's assets in lieu of a cash payment to creditors and those providing estate administration services. This is not possible
   for the payment of taxes-both the federal and state governments require a cash payment within nine months of the decedent's date of death. 
   
   Loans for payments of taxes and other costs: 
   Borrow money to cover estate taxes and administration expeneses of the decedent. 

## Income Tax Issues on Decedent's Final Return 
* Final Tax return must be prepared and filed. The final return will include all of the decedent's taxable and deductions until the date of his death. 
* Expense Elections
  - The executor cannot elect to deduct the same expenses on both returns 
  - If decedent's estate is not subject to the estate taxes, the expenses should be deducted from the decedent's final income tax return 
  - medical expenses are deductible on the final income tax return, AGI is exceeded 7.5% of decedent's adjusted gross income in the year of death. 
  
## Income Tax Issues regarding Form 1041: 
* Selection of tax year: estate is not a natural person, it is not required to use a calendar year for the tax purposes. **The executor can elect to have estate's 
tax year end on the last day of any month during the year. **

* Expense Elections: 

* Waiver of the executor's fees 
* Any casualty losses suffered during estate administration may be deducted on either the fiduciary income tax return or the decedent's estate tax return 
* Waiver of exectuor's fees: executor's fees are deductible either on the fidiciary income tax return. 

US Savings Bonds and income in respect of decedent Assets: 
IRD assets do not receive a step to fmv in basis at the owner's date of death. US Savings Bonds are treaed in this way because usually income tax is not paid on the interest as it accrues-it

- whoever receives the income may receive a corresponding IRD deduction 
- If the decedent has made any charitable bequests in his will, it may be the best ideas to satisfy those bequests with any US savings Bonds and IRD assets. While
charity will recognize income upon the receipt of the asset, no income tax will be paid because charitable organizations are exempt from income tax. 

Some examples of the IRD assets: 
* Qualified Plans 
* IRAs 
* US Saving Bonds 


Gift Tax Issues: 
* Split Gifts for the year of death: 

Giving away assets during their lifetime, not only will the asset be removed from their gross estate, the future appreciation value would be transferred to the donees as well. 

- the gift splitting election treats a gift of separate property as being made one-half from each spouse 
- If the decedent made gifts during the last year before his death, those gifts must be reported on a timely filed gift tax return. 

## Basics Estate Planning Issues: 
- Valuation of Assets 
- Small estate would tend to overstate while the large estate would be vice verser 
A small estate would benefit assigning higher values to its assets, since the value of the assets included in the gross estate receive a step-up in basis for the heirs. 
- Large estates would rather under value the assets and save on estate taxes, even they may generate higher capital taxes to pay. 

AVD: Alternate Valuation Date
The fair market value of the assets six months after the decedent's date of death is included in the gross estate 
Conditions needed to be met for the AVD election: 
(1) The Value of the assets included in the fross estate six months after decedent's date of death must be ##lower## than the value of the assets on the date of death.
(2) There must be a reduction in the total estate tax due as a result of the election 

Some assets are excluded from the AVD election: 
(1) Assets distribued before 6 months which are valued at the date of distribution 
(2) Wasting Assets: patents, royalties, installment notes, lease income 

Installment payments of estate Tax: 
Owner's Interest would be a big problem if they are facing the gross estate inclusion problem since if they died, they have to pay the estate taxes within nine months. 

- When the executor chose the installment payments of estate tax under #section 6166#, they could amortize the estate tax payment within ##14 years## 
- Qualification of the 6166: 
- The value of the business interest must exceed 35% of the value of the decedent's adjusted gross estate 
- Closely held business, and the 20% of total capital interest is included in the decedent's gross estate 
- Actively engaged in the conduct of a trade or a business at the date of decedent's death 

-Special Use Valuation (2032A) 
Purpose: the value of the property may be higher than the value of the property in its current use. 
- If a special use valuation is elected, the value included in the decedent's gross estate will be the current use value of the property, subject to a limitation that the highest and best use value cannot be reduced by more than 1.19 million (2021) 

##Requirements of the special use of evalution: 
-- US residents or citizen at the time of his death 
-- The property must be used as a farming operation or trade business actively managed by the decedent's gross estate. 
-- The value of the real and personal property used in a qualifying manner must equal or exceed 50% of the decedent's gross estate 
-- The value of the real property used in a qualifiying manner must equal or exceed 25% of the value of the gross estate 
-- the property must be located in the US and must pass to qualifying heirs 
-- The executor must file the election with the estate tax return, complete with a recapture 

If the heirs are stopped in using property in a quaifying manner, the property is sold during the 10 year period, the additional tax is imposed. 
The amount is imposed is the lesser of (1) The estate tax savings from special use Valuation (2) amount equal to the proceeds from the sale of the property less special use valuation amount 

## IRC Section6166 
(1) Requirement: 
* 10 annual installment 
* 1.59 mm 
* First installment must be made within 5 years after the estate tax return is due 
* 2% interest on first 1.59 mm of a closely held business interest. It the estate makes use of the lower interest rate, the interest is not deductible. 

eligiblity: 
* value of closely held business interest > 35% of the AGE. Must be sole propriertorship in which the decedent owned 20% capital interest or 20% voting share. 
* If it is more than one business, they can be aggregated to meet the 35% of AGE if the decedent owns 20% of capital interest. 

## IRC Section 2032A 
reduce the fmv of the real property up to 1.19 mm 

eligibility: 
* bueinss real property must be used in farm or business activitiy managed by the decedent or the decedent's family 5 out of 8 years prior to the decedent's death 
* real preoperty must pass to qualifying heirs 
* executor must file election with estate tax return 
* values of business real and personal property must be 50% of the GE as adjusted 

Disclaimers: an irrevocable and unqualified refusal to accept a gift and request 

## Requirements: 
(1) Disclaimer must be in writing 
(2) The disclaimer must be made within nine months of the date on which the transfer creating the interest was made or the day on which the discaliming party reache the age of 21. 
(3) The disclaimer could not specify who they are transferred to. 
(4) the disclaimant cannot accept any interest or benefit in the property prior to disclaiming 

Disclaimer by the surviving spouse: The spouse has the right to turn the estate down 
Disclaimer in favor of surviving spouse: This would be disclaimers by others and make sure the surviving spouse has sufficient fund 
Disclaimer in favor of charities: All the transferred money would qualify for the unlimited charitable deduction in the transferor's estate 
Disclaimer by others ignoring the marital deduction: 
Power of Appointment: the disclaimant has the authority to desigate the recipient of the property as occurs with a general power of appointment 

QTIP election: 
QDOT election: the election must be made by a US citizen spouse or US citizen executor 
GSTT: generation skipping transfer tax elections 

# GSTT Tax: 
The GSTT is an excise tax, in addition to any gift or estate tax, imposed on the transfer of property to a donee who is ## two or more generations younger than the donor. 

## Characteristics of GSTT tax: 
* GSTT system has an annual exclusion of $15,000 life time exemption of 11.7 mm 

The diffeerences between GSTT,estate tax and gift tax, 

11.7 mm, the GSTT tax has imposed 40% rate 2021. GSTT provides lifetime transfer to the skip person. 

Transferor: 
1. Two or more generation than then transferee 
2. when they do the transfer during life, it is subject to gift tax, the transferor is the donor. When the property is transferred at death, and is subject to estate tax. 

Transferee: 
1. The transferee is the individual who receives the property 
2. non skip person and skip person 

Skip Person: 
1. lineal descendant of the transferor's grandparent (or transferor's spous's grandparents), two or more generations younger than the transferor and any person who is not a lineal descedant, is not the spouse of the transferor or is two or more generations younger than the transferor base on age. (37,1/2)
2. The examples of the individuals from the lineal line: 
Transferor's Grandparent: (assumping your are the transferor) 
1. 1st cousin twice removed ( your cousin's second child) 
2. Your sibling's grandniece/nephew, adopted great grand niece/nephew 
3. My grandchild/great-grandchild. 

Unrelated and Nonlineal Descendants for GSTT purposes: 
these people who are more distant and are not related to the transferor 
To determine whether the non-lineal descendants are skip persons, the individual's age is the only relevant factor, which is 37 1/2 

(1) A trust may deem as a skip person only if 
* all interests in the trust are held by skip persons 
* trust distributions can only be made to skip persons 

(2) Charitable organizations are considered to be the same generations as the transferor 

Exceptions: 
1. A child of the transferor is deceased at the time of a transfer, then that child's ddescendants are moved up one generation for purposes of determining whether any transfer made up a GSTT 
Example: If some person's child died, the grandchild would move up to one genration so there is no GSTT tax but gift tax 

Nonskip person: They are regarded as the same generation as the as the spouse. 
A trust is a non-skip person. 

## Types of Taxable Transfers: 
1. direct skip 2. taxable distribution 3 taxable termination 
A direct skip: outright transfer of property to a skip person that is subject to estate or gift tax. 
-- GSTT on a direct skip is imposed on the value received by the tranferee 







 

